version: "3.4"
services:
  db:
    image: postgres:alpine3.18
    restart: unless-stopped
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: poatgres
      POSTGRES_PASSWORD: Dachduna0
      POSTGRES_DB: db
    volumes:
      - db:/var/lib/postgresql/data
    command: -p 5433

volumes:
  db:
