import ClientOnly from "./components/ClientOnly";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/app/providers/AuthProvider";
import ToasterProvider from "@/app/providers/ToasterProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Career Guidance",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ClientOnly>
            <ToasterProvider />
            <Navbar />
          </ClientOnly>
          <div className="py-24">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
